# Generated by Django 5.1.5 on 2025-02-01 20:34

import django.db.models.deletion
import prodzm.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the product.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A detailed description of the product."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product.",
                        max_digits=10,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Shipping cost for this product.",
                        max_digits=10,
                    ),
                ),
                (
                    "remaining_stock",
                    models.PositiveIntegerField(
                        help_text="Remaining stock of this product."
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Product rating (from 0 to 5).",
                        max_digits=3,
                    ),
                ),
                (
                    "orders",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of orders made for this product.",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique Stock Keeping Unit (SKU) for this product.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        help_text="Name of the product supplier.", max_length=255
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category to which this product belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prodzm.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image file for the product.",
                        upload_to=prodzm.utils.product_image_upload_path,
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this image is the main product image.",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product associated with this image.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="prodzm.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ForeignKey(
                help_text="Main image for the product.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_product",
                to="prodzm.productimage",
            ),
        ),
    ]
