# Generated by Django 5.1.5 on 2025-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0002_product_productimage_product_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Customer's first name.", max_length=255
                    ),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Customer's last name.", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Customer's email address (must be unique).",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Customer's phone number (optional).",
                        max_length=15,
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(help_text="Customer's shipping address."),
                ),
            ],
        ),
    ]
