# Generated by Django 5.1.5 on 2025-02-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0003_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the order was created.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        help_text="Current status of the order.",
                        max_length=50,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price of the order.",
                        max_digits=10,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed the order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prodzm.customer",
                    ),
                ),
            ],
        ),
    ]
