# Generated by Django 5.1.5 on 2025-02-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0004_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of the product being ordered."
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product at the time of the order.",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prodzm.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being ordered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prodzm.product",
                    ),
                ),
            ],
        ),
    ]
