# Generated by Django 5.1.5 on 2025-02-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0005_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        help_text="Tracking number for the shipped order.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        help_text="Current shipping status of the order.",
                        max_length=50,
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the order was shipped.",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the order was delivered.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order associated with this shipping info.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prodzm.order",
                    ),
                ),
            ],
        ),
    ]
