# Generated by Django 5.1.5 on 2025-02-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0006_shipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Rating given to the product.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Text feedback or review provided by the customer."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the review was created.",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who left the review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prodzm.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prodzm.product",
                    ),
                ),
            ],
        ),
    ]
