# Generated by Django 5.1.5 on 2025-02-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0007_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="main_image",
        ),
        migrations.AddField(
            model_name="product",
            name="product_images",
            field=models.ForeignKey(
                default=True,
                help_text="Main image for the product.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="prodzm.productimage",
            ),
            preserve_default=False,
        ),
    ]
