# Generated by Django 5.1.5 on 2025-02-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prodzm", "0008_remove_product_main_image_product_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_images",
        ),
    ]
